### ISSUE TITLE
Commenting

### ISSUE THREAD

**Issue by LJanieL** [ocele/CITS5505-Group-Project#12]
After commenting, the page jumps back to language problem

**Comment by Transparencency** [comment]
ocele/CITS5505-Group-Project/@31a6ee1 fixed language problem

**Comment by Transparencency** [comment]
ocele/CITS5505-Group-Project@31a6ee1 fixed language problem

**Comment by Transparencency** [comment]
ocele/CITS5505-Group-Project/@31a6ee1 fixed language problem

**Comment by Transparencency** [comment]
ocele/CITS5505-Group-Project@31a6ee1 fixed language problem
